// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTEOgtX8RdlLflKmyv7EBfBmx2UtVg5JU',
    appId: '1:1042514669062:web:03583910a4ad80ed69dd87',
    messagingSenderId: '1042514669062',
    projectId: 'klam-9999',
    authDomain: 'klam-9999.firebaseapp.com',
    databaseURL: 'https://klam-9999-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'klam-9999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxweVjc_U0P2YRfwlxmONHX3Taw-fPSh4',
    appId: '1:1042514669062:android:62506011887328f569dd87',
    messagingSenderId: '1042514669062',
    projectId: 'klam-9999',
    databaseURL: 'https://klam-9999-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'klam-9999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAV5ljmB0uErwokwFR22mowEX9drOXbE4',
    appId: '1:1042514669062:ios:ff5b28036119218969dd87',
    messagingSenderId: '1042514669062',
    projectId: 'klam-9999',
    databaseURL: 'https://klam-9999-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'klam-9999.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

}